FROM node:16-alpine

WORKDIR /usr/app

COPY ./package.json .
 
# Install dependencies
RUN npm install
 
# Copy the rest of the files
# into the container
COPY . .
 
# Run this
CMD ["npm", "run", "serve"]